export const SCORE_WEIGHTS = {
  clarity: 15,
  specificity: 15,
  context: 10,
  constraints: 10,
  outputFormat: 10,
  examples: 8,
  audience: 7,
  tone: 5,
  predictability: 10,
  completeness: 10,
} as const;

export const PENALTIES = {
  perWeakWord: -2,
  maxWeakWordPenalty: -15,
  perAmbiguityIssue: -3,
  maxAmbiguityPenalty: -12,
  multipleTasksPenalty: -4,
  excessiveVerbosityPenalty: -3,
  contradictionPenalty: -5,
} as const;

export const STRENGTH_THRESHOLDS = {
  Expert: 82,
  Strong: 65,
  Good: 46,
  Fair: 28,
  Weak: 0,
} as const;

export const MIN_PROMPT_WORDS = 12;
export const VERBOSE_THRESHOLD_WORDS = 500;

export const WEAK_WORDS: Array<{ pattern: RegExp; reason: string }> = [
  { pattern: /\bmaybe\b/gi, reason: "Introduces uncertainty — be direct" },
  { pattern: /\bprobably\b/gi, reason: "Hedges commitment — state clearly" },
  { pattern: /\bperhaps\b/gi, reason: "Vague qualifier — remove or replace" },
  { pattern: /\bsomehow\b/gi, reason: "Unclear mechanism — specify how" },
  { pattern: /\bkind of\b/gi, reason: "Imprecise — be specific" },
  { pattern: /\bsort of\b/gi, reason: "Imprecise — be specific" },
  { pattern: /\btry to\b/gi, reason: "Weak imperative — use direct command" },
  { pattern: /\bif possible\b/gi, reason: "Adds unnecessary conditionality" },
  { pattern: /\bcan you\b/gi, reason: "Weak request form — use imperative" },
  { pattern: /\bshould\b/gi, reason: "Ambiguous obligation — use 'must' or 'will'" },
  { pattern: /\bmight\b/gi, reason: "Too uncertain — state what is expected" },
  { pattern: /\bcould\b/gi, reason: "Conditional framing — use direct form" },
  { pattern: /\bas needed\b/gi, reason: "Vague condition — define when/how" },
  { pattern: /\bsomething like\b/gi, reason: "Imprecise — give a concrete example" },
  { pattern: /\bwhatever works\b/gi, reason: "Gives AI too much freedom — constrain it" },
  { pattern: /\banything\b/gi, reason: "Over-broad — narrow the scope" },
  { pattern: /\bbasically\b/gi, reason: "Filler word — remove it" },
  { pattern: /\bessentially\b/gi, reason: "Filler word — remove it" },
  { pattern: /\bvaguely\b/gi, reason: "Self-describes the problem" },
  { pattern: /\baround\b/gi, reason: "Approximation — use exact values if known" },
  { pattern: /\babout\b/gi, reason: "Approximation — be precise where possible" },
  { pattern: /\bsome\b/gi, reason: "Undefined quantity — specify a number or scope" },
  { pattern: /\bfeel free\b/gi, reason: "Over-permissive — define what you want" },
];

export const STRUCTURE_PATTERNS = {
  role: [
    /\byou are\b/i,
    /\bact as\b/i,
    /\bpretend (you are|to be)\b/i,
    /\bbehave as\b/i,
    /\byour role is\b/i,
    /\bas a[n]?\b/i,
    /\bplaying the role\b/i,
  ],
  task: [
    /\b(write|create|generate|produce|draft|build|design|analyze|summarize|explain|list|describe|compare|evaluate|review|suggest|provide|give me|tell me|show me|find|identify|translate)\b/i,
  ],
  context: [
    /\bcontext[:]\b/i,
    /\bbackground[:]\b/i,
    /\bsituation[:]\b/i,
    /\bhere is\b/i,
    /\bthe following\b/i,
    /\bgiven that\b/i,
    /\bfor context\b/i,
    /\bin this case\b/i,
    /\bour (project|company|team|product|app|system)\b/i,
  ],
  constraints: [
    /\bdo not\b/i,
    /\bdon't\b/i,
    /\bavoid\b/i,
    /\bwithout\b/i,
    /\bno more than\b/i,
    /\bat most\b/i,
    /\bmaximum\b/i,
    /\bminimum\b/i,
    /\blimit(ed)? to\b/i,
    /\bmust not\b/i,
    /\bexclude\b/i,
    /\bonly (use|include|show)\b/i,
    /\brestrict\b/i,
  ],
  outputFormat: [
    /\bformat[:]\b/i,
    /\bresponse format\b/i,
    /\bin (json|yaml|xml|markdown|html|csv|table|list|bullet)\b/i,
    /\bas a (list|table|json|yaml|numbered|bullet|paragraph|report|essay)\b/i,
    /\bstructured (as|like|in)\b/i,
    /\binclude (a )?header\b/i,
    /\buse (markdown|bullet points|numbered list)\b/i,
    /\boutput (format|should be|must be)\b/i,
    /\breturn (a|the)? (json|yaml|list|table|report)\b/i,
    /\bpresent (it|the results?) (as|in)\b/i,
  ],
  examples: [
    /\bfor example\b/i,
    /\bsuch as\b/i,
    /\blike this\b/i,
    /\bexample[:]\b/i,
    /\beg[.:]?\b/i,
    /\be\.g\.\b/i,
    /\bsample[:]\b/i,
    /\bhere('s| is) an example\b/i,
    /\bsimilar to\b/i,
    /\bfollow this (pattern|format|example)\b/i,
  ],
  audience: [
    /\bfor (a|an|the)?\s*(beginner|expert|developer|manager|executive|student|professional|non-technical|technical|senior|junior)\b/i,
    /\baudience[:]\b/i,
    /\btarget (audience|reader|user)\b/i,
    /\bwho (will|should) read\b/i,
    /\bthe reader (is|will be)\b/i,
    /\bexplain (to|for) (a|an|the)?\b/i,
    /\bassume (the reader|they|the user)\b/i,
  ],
  tone: [
    /\btone[:]\b/i,
    /\bstyle[:]\b/i,
    /\b(formal|informal|casual|professional|friendly|technical|conversational|authoritative|empathetic)\b/i,
    /\bwrite (in a)?\s*(formal|casual|professional|friendly|technical)\b/i,
    /\bsound (like|as)\b/i,
    /\bkeep (it|the tone)\s*(professional|casual|brief|concise)\b/i,
  ],
  successCriteria: [
    /\bsuccess (criteria|metric|measure)\b/i,
    /\bthe (output|result|response) (should|must|needs to|will)\b/i,
    /\bgoal[:]\b/i,
    /\bexpected (output|result|behavior)\b/i,
    /\byou (have|will have) succeeded when\b/i,
    /\byour response is correct (if|when)\b/i,
    /\bmeasure of success\b/i,
  ],
};
